import { DefaultSupermemoryClient } from "../integrations/supermemory-client";

type CaseDef = {
  label: string;
  record: any;
  searchContext: any;
};

async function main() {
  const client = new DefaultSupermemoryClient();
  const ts = new Date().toISOString();
  const nonce = Date.now();

  const cases: CaseDef[] = [
    {
      label: "project",
      record: {
        schemaVersion: "2.0",
        memoryId: `mem_project_${nonce}`,
        canonicalKey: `scope:project:${nonce}`,
        memoryType: "fact",
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        companyId: "company_web",
        projectId: "project_supermemory_fork",
        userId: null,
        conversationId: `conv_project_${nonce}`,
        memoryScope: "project",
        visibility: "shared",
        sensitivity: "internal",
        writtenBy: "agent_orchestrator",
        approvedBy: "agent_orchestrator",
        promotedFrom: null,
        promotionState: "none",
        promotionReason: null,
        status: "active",
        verificationState: "verified",
        confidence: 0.9,
        importance: "high",
        retention: "project_lifecycle",
        sourceType: "scope_smoke",
        sourceRef: null,
        derivedFrom: ["scope-smoke"],
        contradictionSet: null,
        supersedes: null,
        supersededBy: null,
        effectiveFrom: ts,
        effectiveUntil: null,
        ttl: null,
        expiresAt: null,
        lastValidatedAt: ts,
        retrievalPriority: 1,
        qualityScore: 1,
        dedupKey: `scope:project:${nonce}`,
        tags: ["scope", "project"],
        timestamp: ts,
        content: `Project scope smoke ${nonce}`,
        summary: `Project scope smoke ${nonce}`,
      },
      searchContext: {
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        userId: null,
        conversationId: `conv_project_${nonce}`,
        companyId: "company_web",
        projectId: "project_supermemory_fork",
        provider: "discord",
        channel: "discord",
        surface: "discord",
        nowIso: ts,
        roles: [],
        capabilities: [],
      },
    },
    {
      label: "company",
      record: {
        schemaVersion: "2.0",
        memoryId: `mem_company_${nonce}`,
        canonicalKey: `scope:company:${nonce}`,
        memoryType: "fact",
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        companyId: "company_web",
        projectId: null,
        userId: null,
        conversationId: `conv_company_${nonce}`,
        memoryScope: "company",
        visibility: "shared",
        sensitivity: "internal",
        writtenBy: "agent_orchestrator",
        approvedBy: "agent_orchestrator",
        promotedFrom: null,
        promotionState: "none",
        promotionReason: null,
        status: "active",
        verificationState: "verified",
        confidence: 0.9,
        importance: "high",
        retention: "persistent",
        sourceType: "scope_smoke",
        sourceRef: null,
        derivedFrom: ["scope-smoke"],
        contradictionSet: null,
        supersedes: null,
        supersededBy: null,
        effectiveFrom: ts,
        effectiveUntil: null,
        ttl: null,
        expiresAt: null,
        lastValidatedAt: ts,
        retrievalPriority: 1,
        qualityScore: 1,
        dedupKey: `scope:company:${nonce}`,
        tags: ["scope", "company"],
        timestamp: ts,
        content: `Company scope smoke ${nonce}`,
        summary: `Company scope smoke ${nonce}`,
      },
      searchContext: {
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        userId: null,
        conversationId: `conv_company_${nonce}`,
        companyId: "company_web",
        projectId: null,
        provider: "discord",
        channel: "discord",
        surface: "discord",
        nowIso: ts,
        roles: [],
        capabilities: [],
      },
    },
    {
      label: "user",
      record: {
        schemaVersion: "2.0",
        memoryId: `mem_user_${nonce}`,
        canonicalKey: `scope:user:${nonce}`,
        memoryType: "preference",
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        companyId: null,
        projectId: null,
        userId: "436403292009005066",
        conversationId: `conv_user_${nonce}`,
        memoryScope: "user",
        visibility: "shared",
        sensitivity: "internal",
        writtenBy: "agent_orchestrator",
        approvedBy: "agent_orchestrator",
        promotedFrom: null,
        promotionState: "none",
        promotionReason: null,
        status: "active",
        verificationState: "verified",
        confidence: 0.9,
        importance: "high",
        retention: "persistent",
        sourceType: "scope_smoke",
        sourceRef: null,
        derivedFrom: ["scope-smoke"],
        contradictionSet: null,
        supersedes: null,
        supersededBy: null,
        effectiveFrom: ts,
        effectiveUntil: null,
        ttl: null,
        expiresAt: null,
        lastValidatedAt: ts,
        retrievalPriority: 1,
        qualityScore: 1,
        dedupKey: `scope:user:${nonce}`,
        tags: ["scope", "user"],
        timestamp: ts,
        content: `User scope smoke ${nonce}`,
        summary: `User scope smoke ${nonce}`,
      },
      searchContext: {
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        userId: "436403292009005066",
        conversationId: `conv_user_${nonce}`,
        companyId: null,
        projectId: null,
        provider: "discord",
        channel: "discord",
        surface: "discord",
        nowIso: ts,
        roles: [],
        capabilities: [],
      },
    },
    {
      label: "private",
      record: {
        schemaVersion: "2.0",
        memoryId: `mem_private_${nonce}`,
        canonicalKey: `scope:private:${nonce}`,
        memoryType: "fact",
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        companyId: null,
        projectId: null,
        userId: null,
        conversationId: `conv_private_${nonce}`,
        memoryScope: "agent_private",
        visibility: "private",
        sensitivity: "internal",
        writtenBy: "agent_orchestrator",
        approvedBy: "agent_orchestrator",
        promotedFrom: null,
        promotionState: "none",
        promotionReason: null,
        status: "active",
        verificationState: "verified",
        confidence: 0.9,
        importance: "medium",
        retention: "persistent",
        sourceType: "scope_smoke",
        sourceRef: null,
        derivedFrom: ["scope-smoke"],
        contradictionSet: null,
        supersedes: null,
        supersededBy: null,
        effectiveFrom: ts,
        effectiveUntil: null,
        ttl: null,
        expiresAt: null,
        lastValidatedAt: ts,
        retrievalPriority: 1,
        qualityScore: 1,
        dedupKey: `scope:private:${nonce}`,
        tags: ["scope", "private"],
        timestamp: ts,
        content: `Private scope smoke ${nonce}`,
        summary: `Private scope smoke ${nonce}`,
      },
      searchContext: {
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        userId: null,
        conversationId: `conv_private_${nonce}`,
        companyId: null,
        projectId: null,
        provider: "discord",
        channel: "discord",
        surface: "discord",
        nowIso: ts,
        roles: [],
        capabilities: [],
      },
    },
    {
      label: "cold_storage",
      record: {
        schemaVersion: "2.0",
        memoryId: `mem_archive_${nonce}`,
        canonicalKey: `scope:archive:${nonce}`,
        memoryType: "archive_manifest",
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        companyId: null,
        projectId: "project_supermemory_fork",
        userId: null,
        conversationId: `conv_archive_${nonce}`,
        memoryScope: "cold_storage",
        visibility: "restricted",
        sensitivity: "internal",
        writtenBy: "agent_orchestrator",
        approvedBy: "agent_orchestrator",
        promotedFrom: "project",
        promotionState: "promoted",
        promotionReason: "archive smoke",
        status: "active",
        verificationState: "verified",
        confidence: 0.9,
        importance: "high",
        retention: "archival",
        sourceType: "scope_smoke",
        sourceRef: null,
        derivedFrom: ["scope-smoke"],
        contradictionSet: null,
        supersedes: null,
        supersededBy: null,
        effectiveFrom: ts,
        effectiveUntil: null,
        ttl: null,
        expiresAt: null,
        lastValidatedAt: ts,
        retrievalPriority: 1,
        qualityScore: 1,
        dedupKey: `scope:archive:${nonce}`,
        tags: ["scope", "archive"],
        timestamp: ts,
        content: `Archive scope smoke ${nonce}`,
        summary: `Archive scope smoke ${nonce}`,
      },
      searchContext: {
        agentId: "agent_orchestrator",
        agentName: "Orchestrator",
        agentKind: "orchestrator",
        userId: null,
        conversationId: `conv_archive_${nonce}`,
        companyId: null,
        projectId: "project_supermemory_fork",
        provider: "discord",
        channel: "discord",
        surface: "discord",
        nowIso: ts,
        roles: [],
        capabilities: [],
      },
    },
  ];

  const results: any[] = [];

  for (const testCase of cases) {
    const writeResult = await client.write(testCase.record);
    const searchResults = await client.search({
      context: testCase.searchContext,
      intent: testCase.label === "cold_storage" ? "archive_lookup" : "active_project",
      query: testCase.record.canonicalKey,
      scopes: [testCase.record.memoryScope],
      includeArchived: false,
      includeSuperseded: false,
      limit: 10,
    });

    const match = searchResults.find((r) => r.record.canonicalKey === testCase.record.canonicalKey) ?? searchResults[0];

    results.push({
      label: testCase.label,
      writeMemoryId: writeResult.memoryId,
      searchCount: searchResults.length,
      found: !!match,
      actual: match ? {
        canonicalKey: match.record.canonicalKey,
        memoryScope: match.record.memoryScope,
        visibility: match.record.visibility,
        companyId: match.record.companyId,
        projectId: match.record.projectId,
        userId: match.record.userId,
        conversationId: match.record.conversationId,
      } : null,
    });
  }

  console.log(JSON.stringify({ ok: true, results }, null, 2));
}

main().catch((err) => {
  console.error(err?.stack || err);
  process.exit(1);
});
